[package]
name = "wf-config"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["fs"] }
tracing.workspace = true

toml.workspace = true
regex.workspace = true
glob.workspace = true
wf-types = { path = "../../foundation/wf-types" }
wf-script = { path = "../wf-script" }
wf-common = { path = "../../foundation/wf-common" }
wf-core = { path = "../../foundation/wf-core" }
wf-metrics = { path = "../wf-metrics" }

[dev-dependencies]
tempfile.workspace = true
