/**
 * Assistant System Prompt Template
 * Used to define system prompts for general assistants
 *
 * This template is generated by combining predefined segments and supports the injection of dynamic tool instructions.
 *
 * Fragments must be registered via the unified registration module before using this template.
 */

import type { PromptTemplate } from "@wf-agent/types";
import type { FragmentRegistry } from "../../../../shared/registry/fragment-registry.js";
import {
  ASSISTANT_SYSTEM_PROMPT_FRAGMENTS,
  buildCompleteSystemPrompt,
} from "../fragments/index.js";

/**
 * Construct assistant system prompt content
 *
 * @param toolListDescription Optional dynamic tool descriptions
 * @param fragmentRegistry Fragment registry instance (for lazy evaluation)
 * @returns Complete system prompt content
 */
export function buildAssistantSystemPromptContent(
  toolListDescription?: string,
  fragmentRegistry?: FragmentRegistry,
): string {
  return buildCompleteSystemPrompt({
    fragmentIds: ASSISTANT_SYSTEM_PROMPT_FRAGMENTS,
    toolListDescription,
    fragmentRegistry,
  });
}

/**
 * Assistant System Prompt Words Template
 *
 * This is a template based on the combination of segments, where "content" represents the default combination (excluding tool instructions).
 * Note: content is a function that requires FragmentRegistry to be passed at render time.
 */
export const ASSISTANT_SYSTEM_TEMPLATE: PromptTemplate = {
  id: "system.assistant",
  name: "Assistant System Prompt",
  description: "Generic Assistant System Prompt Words (based on fragment combinations)",
  category: "system",
  content: "Generated from fragments at render time via buildAssistantSystemPromptContent(). See fragments field for the list of fragment IDs.",
  variables: [],
  fragments: ASSISTANT_SYSTEM_PROMPT_FRAGMENTS,
};

/**
 * List of assistant system prompt phrase IDs
 * For custom combination or extension purposes
 */
export { ASSISTANT_SYSTEM_PROMPT_FRAGMENTS };
