/**
 * Programmer System Prompt Template
 * Used to define system prompts for programmer assistants
 *
 * This template is generated by combining predefined segments and supports the injection of dynamic tool instructions.
 *
 * Fragments must be registered via the unified registration module before using this template.
 */

import type { PromptTemplate } from "@wf-agent/types";
import type { FragmentRegistry } from "../../../../shared/registry/fragment-registry.js";
import {
  buildCompleteSystemPrompt,
  CODER_SYSTEM_PROMPT_FRAGMENTS,
} from "../fragments/index.js";

/**
 * Constructing the programmer assistant system prompt content
 *
 * @param toolListDescription (Optional) Description of the dynamic tools
 * @param fragmentRegistry Fragment registry instance (for lazy evaluation)
 * @returns The complete system prompt content
 */
export function buildCoderSystemPromptContent(
  toolListDescription?: string,
  fragmentRegistry?: FragmentRegistry,
): string {
  return buildCompleteSystemPrompt({
    fragmentIds: CODER_SYSTEM_PROMPT_FRAGMENTS,
    toolListDescription,
    fragmentRegistry,
  });
}

/**
 * Programmer System Prompt Template
 *
 * This is a template based on the combination of segments, with "content" being the default combination (excluding tool instructions).
 * Note: content is a function that requires FragmentRegistry to be passed at render time.
 */
export const CODER_SYSTEM_TEMPLATE: PromptTemplate = {
  id: "system.coder",
  name: "Coder System Prompt",
  description: "Programming Assistant System Prompt Words (based on fragment combinations)",
  category: "system",
  content: "",
  variables: [],
  fragments: CODER_SYSTEM_PROMPT_FRAGMENTS,
};

/**
 * List of programmer system prompt phrase IDs
 * Used for custom combination or extension
 */
export { CODER_SYSTEM_PROMPT_FRAGMENTS };
