use wf_types::tool_description::{ToolDescriptionData, ToolParameterDescription};

use crate::registrar::{register_item, Options, Registries};
use crate::result::Summary;

pub fn builtin_tool_descriptions() -> Vec<ToolDescriptionData> {
    vec![
        ToolDescriptionData {
            id: "read_file".into(),
            r#type: "STATELESS".into(),
            category: Some("filesystem".into()),
            description: "Read the contents of a file at the given path. Returns the file content as text.".into(),
            parameters: vec![
                ToolParameterDescription {
                    name: "path".into(),
                    r#type: "string".into(),
                    required: true,
                    description: "Absolute path to the file".into(),
                    default_value: None,
                },
            ],
            tips: Some(vec!["Use absolute paths whenever possible".into()]),
            examples: Some(vec!["read_file(\"/home/user/project/src/main.rs\")".into()]),
        },
        ToolDescriptionData {
            id: "write_file".into(),
            r#type: "STATELESS".into(),
            category: Some("filesystem".into()),
            description: "Write content to a file. Creates the file if it doesn't exist, overwrites if it does.".into(),
            parameters: vec![
                ToolParameterDescription {
                    name: "path".into(),
                    r#type: "string".into(),
                    required: true,
                    description: "Absolute path to the file".into(),
                    default_value: None,
                },
                ToolParameterDescription {
                    name: "content".into(),
                    r#type: "string".into(),
                    required: true,
                    description: "Content to write to the file".into(),
                    default_value: None,
                },
            ],
            tips: Some(vec![
                "Always read the file first before overwriting".into(),
            ]),
            examples: None,
        },
        ToolDescriptionData {
            id: "edit_file".into(),
            r#type: "STATELESS".into(),
            category: Some("filesystem".into()),
            description: "Apply a search-and-replace edit to a file. Finds the first occurrence of old_string and replaces it with new_string.".into(),
            parameters: vec![
                ToolParameterDescription {
                    name: "path".into(),
                    r#type: "string".into(),
                    required: true,
                    description: "Absolute path to the file".into(),
                    default_value: None,
                },
                ToolParameterDescription {
                    name: "old_string".into(),
                    r#type: "string".into(),
                    required: true,
                    description: "Text to search for (must be unique)".into(),
                    default_value: None,
                },
                ToolParameterDescription {
                    name: "new_string".into(),
                    r#type: "string".into(),
                    required: true,
                    description: "Text to replace with".into(),
                    default_value: None,
                },
            ],
            tips: Some(vec![
                "Use unique context around the edit target".into(),
            ]),
            examples: Some(vec!["edit_file(\"src/main.rs\", \"old_function()\", \"new_function()\")".into()]),
        },
        ToolDescriptionData {
            id: "apply_patch".into(),
            r#type: "STATELESS".into(),
            category: Some("filesystem".into()),
            description: "Apply a patch to a file using search-and-replace blocks. Each block specifies old_string and new_string.".into(),
            parameters: vec![
                ToolParameterDescription {
                    name: "path".into(),
                    r#type: "string".into(),
                    required: true,
                    description: "Absolute path to the file".into(),
                    default_value: None,
                },
                ToolParameterDescription {
                    name: "patches".into(),
                    r#type: "array".into(),
                    required: true,
                    description: "List of {old_string, new_string} pairs".into(),
                    default_value: None,
                },
            ],
            tips: None,
            examples: None,
        },
        ToolDescriptionData {
            id: "apply_diff".into(),
            r#type: "STATELESS".into(),
            category: Some("filesystem".into()),
            description: "Apply a unified diff to a file. The diff must be in standard unified format.".into(),
            parameters: vec![
                ToolParameterDescription {
                    name: "path".into(),
                    r#type: "string".into(),
                    required: true,
                    description: "Absolute path to the file".into(),
                    default_value: None,
                },
                ToolParameterDescription {
                    name: "diff".into(),
                    r#type: "string".into(),
                    required: true,
                    description: "Unified diff content".into(),
                    default_value: None,
                },
            ],
            tips: None,
            examples: None,
        },
        ToolDescriptionData {
            id: "list_dir".into(),
            r#type: "STATELESS".into(),
            category: Some("filesystem".into()),
            description: "List files and directories in a given directory path.".into(),
            parameters: vec![
                ToolParameterDescription {
                    name: "path".into(),
                    r#type: "string".into(),
                    required: true,
                    description: "Absolute path to the directory".into(),
                    default_value: None,
                },
            ],
            tips: None,
            examples: Some(vec!["list_dir(\"/home/user/project/src\")".into()]),
        },
        ToolDescriptionData {
            id: "grep_search".into(),
            r#type: "STATELESS".into(),
            category: Some("filesystem".into()),
            description: "Search for a pattern in files using regex. Returns matching file paths and line numbers.".into(),
            parameters: vec![
                ToolParameterDescription {
                    name: "pattern".into(),
                    r#type: "string".into(),
                    required: true,
                    description: "Regex pattern to search for".into(),
                    default_value: None,
                },
                ToolParameterDescription {
                    name: "path".into(),
                    r#type: "string".into(),
                    required: false,
                    description: "Directory to search in".into(),
                    default_value: None,
                },
                ToolParameterDescription {
                    name: "include".into(),
                    r#type: "string".into(),
                    required: false,
                    description: "File glob pattern to include".into(),
                    default_value: None,
                },
            ],
            tips: Some(vec!["Use specific patterns to narrow results".into()]),
            examples: Some(vec!["grep_search(\"fn main\", \".\", \"*.rs\")".into()]),
        },
        ToolDescriptionData {
            id: "glob_search".into(),
            r#type: "STATELESS".into(),
            category: Some("filesystem".into()),
            description: "Find files matching a glob pattern. Returns matching file paths.".into(),
            parameters: vec![
                ToolParameterDescription {
                    name: "pattern".into(),
                    r#type: "string".into(),
                    required: true,
                    description: "Glob pattern to match".into(),
                    default_value: None,
                },
                ToolParameterDescription {
                    name: "path".into(),
                    r#type: "string".into(),
                    required: false,
                    description: "Directory to search in".into(),
                    default_value: None,
                },
            ],
            tips: None,
            examples: Some(vec!["glob_search(\"**/*.rs\", \"/home/user/project\")".into()]),
        },
        ToolDescriptionData {
            id: "execute_command".into(),
            r#type: "STATELESS".into(),
            category: Some("shell".into()),
            description: "Execute a shell command and return its output.".into(),
            parameters: vec![
                ToolParameterDescription {
                    name: "command".into(),
                    r#type: "string".into(),
                    required: true,
                    description: "Shell command to execute".into(),
                    default_value: None,
                },
                ToolParameterDescription {
                    name: "workdir".into(),
                    r#type: "string".into(),
                    required: false,
                    description: "Working directory for the command".into(),
                    default_value: None,
                },
                ToolParameterDescription {
                    name: "timeout".into(),
                    r#type: "number".into(),
                    required: false,
                    description: "Timeout in seconds".into(),
                    default_value: Some(serde_json::json!(30)),
                },
            ],
            tips: Some(vec![
                "Use absolute paths for safety".into(),
                "Avoid interactive commands".into(),
            ]),
            examples: Some(vec!["execute_command(\"cargo build\")".into()]),
        },
        ToolDescriptionData {
            id: "web_search".into(),
            r#type: "STATELESS".into(),
            category: Some("http".into()),
            description: "Search the web for information. Returns search results with snippets.".into(),
            parameters: vec![
                ToolParameterDescription {
                    name: "query".into(),
                    r#type: "string".into(),
                    required: true,
                    description: "Search query".into(),
                    default_value: None,
                },
                ToolParameterDescription {
                    name: "max_results".into(),
                    r#type: "number".into(),
                    required: false,
                    description: "Maximum number of results to return".into(),
                    default_value: Some(serde_json::json!(5)),
                },
            ],
            tips: Some(vec!["Be specific in your queries for better results".into()]),
            examples: Some(vec!["web_search(\"Rust async programming best practices\")".into()]),
        },
        ToolDescriptionData {
            id: "web_fetch".into(),
            r#type: "STATELESS".into(),
            category: Some("http".into()),
            description: "Fetch content from a URL and return it as text.".into(),
            parameters: vec![
                ToolParameterDescription {
                    name: "url".into(),
                    r#type: "string".into(),
                    required: true,
                    description: "URL to fetch".into(),
                    default_value: None,
                },
                ToolParameterDescription {
                    name: "format".into(),
                    r#type: "string".into(),
                    required: false,
                    description: "Response format (text, markdown, html)".into(),
                    default_value: Some(serde_json::json!("markdown")),
                },
            ],
            tips: Some(vec!["Prefer markdown format for readability".into()]),
            examples: Some(vec!["web_fetch(\"https://example.com\")".into()]),
        },
        ToolDescriptionData {
            id: "skill".into(),
            r#type: "STATELESS".into(),
            category: Some("builtin".into()),
            description: "Load and execute a skill by name. Skills provide structured workflows for common tasks.".into(),
            parameters: vec![
                ToolParameterDescription {
                    name: "skill".into(),
                    r#type: "string".into(),
                    required: true,
                    description: "Skill name to invoke".into(),
                    default_value: None,
                },
                ToolParameterDescription {
                    name: "args".into(),
                    r#type: "object".into(),
                    required: false,
                    description: "Arguments to pass to the skill".into(),
                    default_value: None,
                },
            ],
            tips: None,
            examples: Some(vec!["skill(\"analyze-data\", {\"path\": \"/data.csv\"})".into()]),
        },
        ToolDescriptionData {
            id: "use_mcp".into(),
            r#type: "STATELESS".into(),
            category: Some("builtin".into()),
            description: "Use a tool from an MCP (Model Context Protocol) server. Allows extending capabilities dynamically.".into(),
            parameters: vec![
                ToolParameterDescription {
                    name: "server_name".into(),
                    r#type: "string".into(),
                    required: true,
                    description: "MCP server name".into(),
                    default_value: None,
                },
                ToolParameterDescription {
                    name: "tool_name".into(),
                    r#type: "string".into(),
                    required: false,
                    description: "Tool name on the server".into(),
                    default_value: None,
                },
                ToolParameterDescription {
                    name: "arguments".into(),
                    r#type: "object".into(),
                    required: false,
                    description: "Arguments for the tool".into(),
                    default_value: None,
                },
            ],
            tips: None,
            examples: Some(vec!["use_mcp(\"database\", \"query\", {\"sql\": \"SELECT * FROM users\"})".into()]),
        },
        ToolDescriptionData {
            id: "record_note".into(),
            r#type: "STATEFUL".into(),
            category: Some("memory".into()),
            description: "Record a note in memory with an optional category. Notes can be recalled later.".into(),
            parameters: vec![
                ToolParameterDescription {
                    name: "content".into(),
                    r#type: "string".into(),
                    required: true,
                    description: "Note content to remember".into(),
                    default_value: None,
                },
                ToolParameterDescription {
                    name: "category".into(),
                    r#type: "string".into(),
                    required: false,
                    description: "Optional category for grouping notes".into(),
                    default_value: None,
                },
            ],
            tips: None,
            examples: Some(vec!["record_note(\"User prefers dark mode\", \"preferences\")".into()]),
        },
        ToolDescriptionData {
            id: "recall_notes".into(),
            r#type: "STATEFUL".into(),
            category: Some("memory".into()),
            description: "Recall previously recorded notes, optionally filtered by category.".into(),
            parameters: vec![
                ToolParameterDescription {
                    name: "category".into(),
                    r#type: "string".into(),
                    required: false,
                    description: "Filter by category".into(),
                    default_value: None,
                },
            ],
            tips: None,
            examples: Some(vec!["recall_notes(\"preferences\")".into()]),
        },
        ToolDescriptionData {
            id: "backend_shell".into(),
            r#type: "STATEFUL".into(),
            category: Some("shell".into()),
            description: "Start a long-running shell command in the background. Returns a shell_id for later interaction.".into(),
            parameters: vec![
                ToolParameterDescription {
                    name: "command".into(),
                    r#type: "string".into(),
                    required: true,
                    description: "Shell command to execute".into(),
                    default_value: None,
                },
                ToolParameterDescription {
                    name: "cwd".into(),
                    r#type: "string".into(),
                    required: false,
                    description: "Working directory".into(),
                    default_value: None,
                },
            ],
            tips: Some(vec!["Use for long-running processes like dev servers".into()]),
            examples: Some(vec!["backend_shell(\"npm run dev\")".into()]),
        },
        ToolDescriptionData {
            id: "shell_output".into(),
            r#type: "STATEFUL".into(),
            category: Some("shell".into()),
            description: "Get the output from a background shell process by its shell_id.".into(),
            parameters: vec![
                ToolParameterDescription {
                    name: "shell_id".into(),
                    r#type: "string".into(),
                    required: true,
                    description: "ID of the background shell process".into(),
                    default_value: None,
                },
                ToolParameterDescription {
                    name: "filter_str".into(),
                    r#type: "string".into(),
                    required: false,
                    description: "Optional filter string to narrow output".into(),
                    default_value: None,
                },
            ],
            tips: None,
            examples: Some(vec!["shell_output(\"abc123\")".into()]),
        },
        ToolDescriptionData {
            id: "shell_kill".into(),
            r#type: "STATEFUL".into(),
            category: Some("shell".into()),
            description: "Stop a background shell process by its shell_id.".into(),
            parameters: vec![
                ToolParameterDescription {
                    name: "shell_id".into(),
                    r#type: "string".into(),
                    required: true,
                    description: "ID of the background shell process to kill".into(),
                    default_value: None,
                },
            ],
            tips: None,
            examples: Some(vec!["shell_kill(\"abc123\")".into()]),
        },
        ToolDescriptionData {
            id: "memory_remember".into(),
            r#type: "STATELESS".into(),
            category: Some("memory".into()),
            description: "Store a piece of information in memory for later recall.".into(),
            parameters: vec![
                ToolParameterDescription {
                    name: "key".into(),
                    r#type: "string".into(),
                    required: true,
                    description: "Memory key identifier".into(),
                    default_value: None,
                },
                ToolParameterDescription {
                    name: "value".into(),
                    r#type: "string".into(),
                    required: true,
                    description: "Content to remember".into(),
                    default_value: None,
                },
            ],
            tips: None,
            examples: Some(vec!["memory_remember(\"user_name\", \"Alice\")".into()]),
        },
        ToolDescriptionData {
            id: "memory_forget".into(),
            r#type: "STATELESS".into(),
            category: Some("memory".into()),
            description: "Remove a piece of information from memory.".into(),
            parameters: vec![
                ToolParameterDescription {
                    name: "key".into(),
                    r#type: "string".into(),
                    required: true,
                    description: "Memory key to forget".into(),
                    default_value: None,
                },
            ],
            tips: None,
            examples: Some(vec!["memory_forget(\"user_name\")".into()]),
        },
        ToolDescriptionData {
            id: "memory_list".into(),
            r#type: "STATELESS".into(),
            category: Some("memory".into()),
            description: "List all stored memories with their keys and values.".into(),
            parameters: vec![],
            tips: None,
            examples: Some(vec!["memory_list()".into()]),
        },
        ToolDescriptionData {
            id: "ask_followup_question".into(),
            r#type: "BUILTIN".into(),
            category: Some("interaction".into()),
            description: "Ask the user follow-up questions when more information is needed to complete the task.".into(),
            parameters: vec![
                ToolParameterDescription {
                    name: "questions".into(),
                    r#type: "array".into(),
                    required: true,
                    description: "List of 1-3 questions to ask the user".into(),
                    default_value: None,
                },
            ],
            tips: Some(vec!["Be concise, ask one question at a time when possible".into()]),
            examples: Some(vec!["ask_followup_question([\"What is the target directory?\"])".into()]),
        },
        ToolDescriptionData {
            id: "attempt_completion".into(),
            r#type: "BUILTIN".into(),
            category: Some("interaction".into()),
            description: "Signal that the task is complete and present the final result to the user.".into(),
            parameters: vec![
                ToolParameterDescription {
                    name: "data".into(),
                    r#type: "string".into(),
                    required: false,
                    description: "Data or summary to present".into(),
                    default_value: None,
                },
            ],
            tips: Some(vec!["Only call this when the task is fully complete".into()]),
            examples: Some(vec!["attempt_completion(\"Task complete. Created 3 files.\")".into()]),
        },
        ToolDescriptionData {
            id: "execute_workflow".into(),
            r#type: "BUILTIN".into(),
            category: Some("workflow".into()),
            description: "Execute a predefined workflow by its ID. Workflows are multi-step automation sequences.".into(),
            parameters: vec![
                ToolParameterDescription {
                    name: "workflow_id".into(),
                    r#type: "string".into(),
                    required: true,
                    description: "ID of the workflow to execute".into(),
                    default_value: None,
                },
                ToolParameterDescription {
                    name: "input".into(),
                    r#type: "object".into(),
                    required: false,
                    description: "Input parameters for the workflow".into(),
                    default_value: None,
                },
                ToolParameterDescription {
                    name: "wait_for_completion".into(),
                    r#type: "boolean".into(),
                    required: false,
                    description: "Whether to wait for the workflow to finish".into(),
                    default_value: Some(serde_json::json!(true)),
                },
            ],
            tips: None,
            examples: Some(vec!["execute_workflow(\"llm_summary\", {\"text\": \"...\"})".into()]),
        },
        ToolDescriptionData {
            id: "query_workflow_status".into(),
            r#type: "BUILTIN".into(),
            category: Some("workflow".into()),
            description: "Query the status of a running or completed workflow.".into(),
            parameters: vec![
                ToolParameterDescription {
                    name: "workflow_id".into(),
                    r#type: "string".into(),
                    required: true,
                    description: "ID of the workflow to query".into(),
                    default_value: None,
                },
            ],
            tips: None,
            examples: Some(vec!["query_workflow_status(\"wf-123\")".into()]),
        },
        ToolDescriptionData {
            id: "cancel_workflow".into(),
            r#type: "BUILTIN".into(),
            category: Some("workflow".into()),
            description: "Cancel a running workflow by its ID.".into(),
            parameters: vec![
                ToolParameterDescription {
                    name: "workflow_id".into(),
                    r#type: "string".into(),
                    required: true,
                    description: "ID of the workflow to cancel".into(),
                    default_value: None,
                },
            ],
            tips: None,
            examples: Some(vec!["cancel_workflow(\"wf-123\")".into()]),
        },
        ToolDescriptionData {
            id: "call_agent".into(),
            r#type: "BUILTIN".into(),
            category: Some("agent".into()),
            description: "Delegate a task to a sub-agent with a specific profile. The agent runs autonomously.".into(),
            parameters: vec![
                ToolParameterDescription {
                    name: "agent_profile_id".into(),
                    r#type: "string".into(),
                    required: true,
                    description: "Profile ID of the agent to invoke".into(),
                    default_value: None,
                },
                ToolParameterDescription {
                    name: "prompt".into(),
                    r#type: "string".into(),
                    required: true,
                    description: "Task prompt for the agent".into(),
                    default_value: None,
                },
            ],
            tips: None,
            examples: Some(vec!["call_agent(\"code-reviewer\", \"Review the code in src/\")".into()]),
        },
    ]
}

pub fn register(regs: &Registries, opts: &Options) -> Summary {
    let mut total = Summary::new();
    for td in builtin_tool_descriptions() {
        let id = td.id.clone();
        total.merge(register_item(
            &regs.tool_descriptions,
            id,
            td,
            opts.skip_if_exists,
        ));
    }
    total
}
