use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum EventType {
    WorkflowExecutionStarted,
    WorkflowExecutionCompleted,
    WorkflowExecutionFailed,
    WorkflowExecutionPaused,
    WorkflowExecutionResumed,
    WorkflowExecutionCancelled,
    WorkflowExecutionStateChanged,
    WorkflowExecutionForkStarted,
    WorkflowExecutionForkCompleted,
    WorkflowExecutionJoinStarted,
    WorkflowExecutionJoinConditionMet,
    WorkflowExecutionJoinCompleted,
    WorkflowExecutionJoinFailed,
    WorkflowExecutionCopyStarted,
    WorkflowExecutionCopyCompleted,
    NodeStarted,
    NodeCompleted,
    NodeFailed,
    NodeSkipped,
    NodeCustomEvent,
    ForkStarted,
    ForkBranchStarted,
    ForkBranchCompleted,
    ForkCompleted,
    TokenLimitExceeded,
    TokenUsageWarning,
    ContextCompressionRequested,
    ContextCompressionCompleted,
    /// A triggered (nested) agent result was written back to the parent
    /// agent conversation (replace or append). Carries the anchor version
    /// the write-back was produced from; the conversation consumer applies
    /// it only while the session is still at that version.
    ConversationWritebackCompleted,
    MessageAdded,
    MessageContextUpdated,
    NotificationSent,
    ToolCallStarted,
    ToolCallCompleted,
    ToolCallFailed,
    ToolCallBlocked,
    ToolAdded,
    ToolVisibilityChanged,
    ConversationStateChanged,
    Error,
    CheckpointCreated,
    CheckpointRestored,
    CheckpointDeleted,
    CheckpointFailed,
    SubgraphStarted,
    SubgraphCompleted,
    TriggeredSubgraphStarted,
    TriggeredSubgraphCompleted,
    TriggeredSubgraphFailed,
    VariableChanged,
    ToolApprovalRequested,
    ToolApprovalResponded,
    ToolApprovalFailed,
    FollowupQuestionRequested,
    FollowupQuestionResponded,
    FollowupQuestionFailed,
    LlmStreamAborted,
    LlmStreamError,
    /// A non-streaming LLM request was issued (online visibility).
    LlmRequested,
    /// A non-streaming LLM request completed successfully.
    LlmResponded,
    /// A non-streaming LLM request failed.
    LlmFailed,
    SkillLoadStarted,
    SkillLoadCompleted,
    SkillLoadFailed,
    AsyncCompletionRegistered,
    AsyncCompletionTriggered,
    AsyncCompletionErrorTriggered,
    AsyncCompletionFailed,
    AsyncCompletionCleanedUp,
    AgentStarted,
    AgentCompleted,
    AgentTurnStarted,
    AgentTurnCompleted,
    AgentMessageStarted,
    AgentMessageCompleted,
    AgentToolExecutionStarted,
    AgentToolExecutionCompleted,
    TimeoutRegistered,
    TimeoutExpired,
    TimeoutCancelled,
    TimeoutWarning,
    AgentIterationStarted,
    AgentIterationCompleted,
    HookTriggered,
    AgentPaused,
    AgentCancelled,
    AgentResumed,
    AgentFailed,
    ExecutionPaused,
    ExecutionCancelled,
    ExecutionResumed,
    ProgressiveToolExecutionStart,
    ProgressiveToolExecutionEnd,
    ToolQueueUpdate,
    ToolApprovalAnnotated,
    NodeSyncStarted,
    NodeSyncCompleted,
    NodeSyncFailed,
    AttemptCompletion,
    ExecutionStopped,
    AgentSteeringInjected,
    AgentFollowupQueued,
    WorkflowExecutionTriggered,
    WorkflowExecutionSubgraphStarted,
    WorkflowExecutionSubgraphCompleted,
    LlmStreamChunk,
    LlmStreamDone,
    ToolCallEdited,
    ToolCallApproved,
    ToolCallDenied,
    ToolConfigUpdated,
    ScriptStarted,
    ScriptCompleted,
    ScriptFailed,
    AllBranchesCompleted,
    Heartbeat,
    SystemMaintenance,
    CheckpointRestoreStarted,
    CheckpointRestoreCompleted,
    /// A file change was recorded into a file-checkpoint actor partition
    /// (agent edit / manual edit / merge). The event payload carries the
    /// `DeltaSummary` (file / source / timestamp).
    CheckpointFileChanged,
    /// A merge produced conflicts (marker strategy applied).
    CheckpointMergeConflicted,
    /// A file-checkpoint garbage collection run completed. The event
    /// payload carries the `GCStats` (removed checkpoints / snapshots /
    /// freed bytes).
    CheckpointGcCompleted,
    ExecutionTimeoutWarning,
    ExecutionTimeoutExpired,
    ShellSessionCreated,
    ShellCommandStarted,
    ShellOutputReceived,
    ShellCommandCompleted,
    ShellSessionTerminated,
}

impl EventType {
    /// Canonical SCREAMING_SNAKE_CASE serialized name of the event type.
    ///
    /// Mirrors the serde `rename_all = "SCREAMING_SNAKE_CASE"` representation
    /// so consumers can match typed events against string-configured
    /// conditions without a serialization round trip.
    pub fn as_str(&self) -> &'static str {
        match self {
            EventType::WorkflowExecutionStarted => "WORKFLOW_EXECUTION_STARTED",
            EventType::WorkflowExecutionCompleted => "WORKFLOW_EXECUTION_COMPLETED",
            EventType::WorkflowExecutionFailed => "WORKFLOW_EXECUTION_FAILED",
            EventType::WorkflowExecutionPaused => "WORKFLOW_EXECUTION_PAUSED",
            EventType::WorkflowExecutionResumed => "WORKFLOW_EXECUTION_RESUMED",
            EventType::WorkflowExecutionCancelled => "WORKFLOW_EXECUTION_CANCELLED",
            EventType::WorkflowExecutionStateChanged => "WORKFLOW_EXECUTION_STATE_CHANGED",
            EventType::WorkflowExecutionForkStarted => "WORKFLOW_EXECUTION_FORK_STARTED",
            EventType::WorkflowExecutionForkCompleted => "WORKFLOW_EXECUTION_FORK_COMPLETED",
            EventType::WorkflowExecutionJoinStarted => "WORKFLOW_EXECUTION_JOIN_STARTED",
            EventType::WorkflowExecutionJoinConditionMet => "WORKFLOW_EXECUTION_JOIN_CONDITION_MET",
            EventType::WorkflowExecutionJoinCompleted => "WORKFLOW_EXECUTION_JOIN_COMPLETED",
            EventType::WorkflowExecutionJoinFailed => "WORKFLOW_EXECUTION_JOIN_FAILED",
            EventType::WorkflowExecutionCopyStarted => "WORKFLOW_EXECUTION_COPY_STARTED",
            EventType::WorkflowExecutionCopyCompleted => "WORKFLOW_EXECUTION_COPY_COMPLETED",
            EventType::NodeStarted => "NODE_STARTED",
            EventType::NodeCompleted => "NODE_COMPLETED",
            EventType::NodeFailed => "NODE_FAILED",
            EventType::NodeSkipped => "NODE_SKIPPED",
            EventType::NodeCustomEvent => "NODE_CUSTOM_EVENT",
            EventType::ForkStarted => "FORK_STARTED",
            EventType::ForkBranchStarted => "FORK_BRANCH_STARTED",
            EventType::ForkBranchCompleted => "FORK_BRANCH_COMPLETED",
            EventType::ForkCompleted => "FORK_COMPLETED",
            EventType::TokenLimitExceeded => "TOKEN_LIMIT_EXCEEDED",
            EventType::TokenUsageWarning => "TOKEN_USAGE_WARNING",
            EventType::ContextCompressionRequested => "CONTEXT_COMPRESSION_REQUESTED",
            EventType::ContextCompressionCompleted => "CONTEXT_COMPRESSION_COMPLETED",
            EventType::ConversationWritebackCompleted => "CONVERSATION_WRITEBACK_COMPLETED",
            EventType::MessageAdded => "MESSAGE_ADDED",
            EventType::MessageContextUpdated => "MESSAGE_CONTEXT_UPDATED",
            EventType::NotificationSent => "NOTIFICATION_SENT",
            EventType::ToolCallStarted => "TOOL_CALL_STARTED",
            EventType::ToolCallCompleted => "TOOL_CALL_COMPLETED",
            EventType::ToolCallFailed => "TOOL_CALL_FAILED",
            EventType::ToolCallBlocked => "TOOL_CALL_BLOCKED",
            EventType::ToolAdded => "TOOL_ADDED",
            EventType::ToolVisibilityChanged => "TOOL_VISIBILITY_CHANGED",
            EventType::ConversationStateChanged => "CONVERSATION_STATE_CHANGED",
            EventType::Error => "ERROR",
            EventType::CheckpointCreated => "CHECKPOINT_CREATED",
            EventType::CheckpointRestored => "CHECKPOINT_RESTORED",
            EventType::CheckpointDeleted => "CHECKPOINT_DELETED",
            EventType::CheckpointFailed => "CHECKPOINT_FAILED",
            EventType::SubgraphStarted => "SUBGRAPH_STARTED",
            EventType::SubgraphCompleted => "SUBGRAPH_COMPLETED",
            EventType::TriggeredSubgraphStarted => "TRIGGERED_SUBGRAPH_STARTED",
            EventType::TriggeredSubgraphCompleted => "TRIGGERED_SUBGRAPH_COMPLETED",
            EventType::TriggeredSubgraphFailed => "TRIGGERED_SUBGRAPH_FAILED",
            EventType::VariableChanged => "VARIABLE_CHANGED",
            EventType::ToolApprovalRequested => "TOOL_APPROVAL_REQUESTED",
            EventType::ToolApprovalResponded => "TOOL_APPROVAL_RESPONDED",
            EventType::ToolApprovalFailed => "TOOL_APPROVAL_FAILED",
            EventType::FollowupQuestionRequested => "FOLLOWUP_QUESTION_REQUESTED",
            EventType::FollowupQuestionResponded => "FOLLOWUP_QUESTION_RESPONDED",
            EventType::FollowupQuestionFailed => "FOLLOWUP_QUESTION_FAILED",
            EventType::LlmStreamAborted => "LLM_STREAM_ABORTED",
            EventType::LlmStreamError => "LLM_STREAM_ERROR",
            EventType::LlmRequested => "LLM_REQUESTED",
            EventType::LlmResponded => "LLM_RESPONDED",
            EventType::LlmFailed => "LLM_FAILED",
            EventType::SkillLoadStarted => "SKILL_LOAD_STARTED",
            EventType::SkillLoadCompleted => "SKILL_LOAD_COMPLETED",
            EventType::SkillLoadFailed => "SKILL_LOAD_FAILED",
            EventType::AsyncCompletionRegistered => "ASYNC_COMPLETION_REGISTERED",
            EventType::AsyncCompletionTriggered => "ASYNC_COMPLETION_TRIGGERED",
            EventType::AsyncCompletionErrorTriggered => "ASYNC_COMPLETION_ERROR_TRIGGERED",
            EventType::AsyncCompletionFailed => "ASYNC_COMPLETION_FAILED",
            EventType::AsyncCompletionCleanedUp => "ASYNC_COMPLETION_CLEANED_UP",
            EventType::AgentStarted => "AGENT_STARTED",
            EventType::AgentCompleted => "AGENT_COMPLETED",
            EventType::AgentTurnStarted => "AGENT_TURN_STARTED",
            EventType::AgentTurnCompleted => "AGENT_TURN_COMPLETED",
            EventType::AgentMessageStarted => "AGENT_MESSAGE_STARTED",
            EventType::AgentMessageCompleted => "AGENT_MESSAGE_COMPLETED",
            EventType::AgentToolExecutionStarted => "AGENT_TOOL_EXECUTION_STARTED",
            EventType::AgentToolExecutionCompleted => "AGENT_TOOL_EXECUTION_COMPLETED",
            EventType::TimeoutRegistered => "TIMEOUT_REGISTERED",
            EventType::TimeoutExpired => "TIMEOUT_EXPIRED",
            EventType::TimeoutCancelled => "TIMEOUT_CANCELLED",
            EventType::TimeoutWarning => "TIMEOUT_WARNING",
            EventType::AgentIterationStarted => "AGENT_ITERATION_STARTED",
            EventType::AgentIterationCompleted => "AGENT_ITERATION_COMPLETED",
            EventType::HookTriggered => "HOOK_TRIGGERED",
            EventType::AgentPaused => "AGENT_PAUSED",
            EventType::AgentCancelled => "AGENT_CANCELLED",
            EventType::AgentResumed => "AGENT_RESUMED",
            EventType::AgentFailed => "AGENT_FAILED",
            EventType::ExecutionPaused => "EXECUTION_PAUSED",
            EventType::ExecutionCancelled => "EXECUTION_CANCELLED",
            EventType::ExecutionResumed => "EXECUTION_RESUMED",
            EventType::ProgressiveToolExecutionStart => "PROGRESSIVE_TOOL_EXECUTION_START",
            EventType::ProgressiveToolExecutionEnd => "PROGRESSIVE_TOOL_EXECUTION_END",
            EventType::ToolQueueUpdate => "TOOL_QUEUE_UPDATE",
            EventType::ToolApprovalAnnotated => "TOOL_APPROVAL_ANNOTATED",
            EventType::NodeSyncStarted => "NODE_SYNC_STARTED",
            EventType::NodeSyncCompleted => "NODE_SYNC_COMPLETED",
            EventType::NodeSyncFailed => "NODE_SYNC_FAILED",
            EventType::AttemptCompletion => "ATTEMPT_COMPLETION",
            EventType::ExecutionStopped => "EXECUTION_STOPPED",
            EventType::AgentSteeringInjected => "AGENT_STEERING_INJECTED",
            EventType::AgentFollowupQueued => "AGENT_FOLLOWUP_QUEUED",
            EventType::WorkflowExecutionTriggered => "WORKFLOW_EXECUTION_TRIGGERED",
            EventType::WorkflowExecutionSubgraphStarted => "WORKFLOW_EXECUTION_SUBGRAPH_STARTED",
            EventType::WorkflowExecutionSubgraphCompleted => {
                "WORKFLOW_EXECUTION_SUBGRAPH_COMPLETED"
            }
            EventType::LlmStreamChunk => "LLM_STREAM_CHUNK",
            EventType::LlmStreamDone => "LLM_STREAM_DONE",
            EventType::ToolCallEdited => "TOOL_CALL_EDITED",
            EventType::ToolCallApproved => "TOOL_CALL_APPROVED",
            EventType::ToolCallDenied => "TOOL_CALL_DENIED",
            EventType::ToolConfigUpdated => "TOOL_CONFIG_UPDATED",
            EventType::ScriptStarted => "SCRIPT_STARTED",
            EventType::ScriptCompleted => "SCRIPT_COMPLETED",
            EventType::ScriptFailed => "SCRIPT_FAILED",
            EventType::AllBranchesCompleted => "ALL_BRANCHES_COMPLETED",
            EventType::Heartbeat => "HEARTBEAT",
            EventType::SystemMaintenance => "SYSTEM_MAINTENANCE",
            EventType::CheckpointRestoreStarted => "CHECKPOINT_RESTORE_STARTED",
            EventType::CheckpointRestoreCompleted => "CHECKPOINT_RESTORE_COMPLETED",
            EventType::CheckpointFileChanged => "CHECKPOINT_FILE_CHANGED",
            EventType::CheckpointMergeConflicted => "CHECKPOINT_MERGE_CONFLICTED",
            EventType::CheckpointGcCompleted => "CHECKPOINT_GC_COMPLETED",
            EventType::ExecutionTimeoutWarning => "EXECUTION_TIMEOUT_WARNING",
            EventType::ExecutionTimeoutExpired => "EXECUTION_TIMEOUT_EXPIRED",
            EventType::ShellSessionCreated => "SHELL_SESSION_CREATED",
            EventType::ShellCommandStarted => "SHELL_COMMAND_STARTED",
            EventType::ShellOutputReceived => "SHELL_OUTPUT_RECEIVED",
            EventType::ShellCommandCompleted => "SHELL_COMMAND_COMPLETED",
            EventType::ShellSessionTerminated => "SHELL_SESSION_TERMINATED",
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct BaseEvent {
    pub id: super::super::Id,
    pub r#type: EventType,
    pub timestamp: super::super::Timestamp,
    /// Secondary event discriminator.
    /// `NODE_CUSTOM_EVENT`-style events carry their concrete name here;
    /// trigger conditions match it alongside `event_type` when configured.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub event_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub workflow_id: Option<super::super::Id>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub execution_id: Option<super::super::Id>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub agent_loop_id: Option<super::super::Id>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metadata: Option<super::super::Metadata>,
}

pub type EventListener = Box<dyn Fn(&BaseEvent) + Send + Sync>;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct EventHandler {
    pub event_type: EventType,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ListenerOptions {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub priority: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub timeout: Option<u64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub execution_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub auto_cleanup: Option<bool>,
}
