pub mod agent_dbg;
pub mod assert;
pub mod branches;
pub mod checkpoints;
pub mod cli;
pub mod cost;
pub mod format;
pub mod hook_dbg;
pub mod import;
pub mod input;
pub mod interactions;
pub mod interruptions;
pub mod loops;
pub mod merges;
pub mod model;
pub mod observe;
pub mod policy;
pub mod replay;
pub mod report;
pub mod runner;
pub mod step;
pub mod subexec;
pub mod timeline;
pub mod trace;
pub mod traverse;
pub mod trigger_dbg;
pub mod views;

pub use model::{Trace, TraceKind};
pub use replay::{replay_trace, ReplayOutcome};
pub use report::{SectionReport, UnifiedReport};
pub use runner::{run_check, CheckOutcome};
