# wf-agent Python wasm guest example (componentize-py).
#
# `componentize-py componentize` generates the real `wit_world` bindings on
# the fly and wraps this package into `plugin.wasm`. Only `exports.py` needs
# to be edited by plugin authors; the stub bindings are regenerated by the
# `bindings` make target.

from .exports import Contributions, Lifecycle

__all__ = ["Contributions", "Lifecycle"]
