/**
 * AgentLoopCoordinator - Agent Loop Lifecycle Coordinator
 *
 * Coordinates the full lifecycle management of AgentLoopEntities.
 * Refer to the design pattern of WorkflowLifecycleCoordinator.
 */

import type { ID } from "@wf-agent/types";
import type { AgentLoopRuntimeConfig, AgentLoopResult } from "@wf-agent/types";
import { getAvailableTools } from "@wf-agent/types";
import type { EventRegistry } from "../../../core/registry/event-registry.js";
import { AgentLoopEntity } from "../../entities/agent-loop-entity.js";
import { AgentLoopStatus } from "@wf-agent/types";
import { AgentLoopFactory, type AgentLoopEntityOptions } from "../../execution/factories/index.js";
import { AgentLoopRegistry } from "../../stores/agent-loop-registry.js";
import { AgentLoopExecutor, type AgentLoopStreamEvent } from "../executors/agent-loop-executor.js";
import { createContextualLogger } from "../../../utils/contextual-logger.js";
import type { GlobalContext } from "../../../core/global-context.js";
import { AgentLoopStateTransitor } from "./agent-loop-state-transitor.js";
import type { AgentLoopMetricsCollector } from "../../../core/metrics/agent-loop-collector.js";
import { now } from "@wf-agent/common-utils";
import * as Identifiers from "../../../core/di/service-identifiers.js";
import type { InterruptionStateFactory } from "../../../core/di/factory-types.js";
import type { InterruptionState } from "../../../core/utils/interruption/interruption-state.js";
import type { AgentStateCoordinator } from "../../state-managers/agent-state-coordinator.js";

const logger = createContextualLogger({ component: "AgentLoopCoordinator" });

/**
 * Execute the option
 */
export interface AgentLoopExecuteOptions extends AgentLoopEntityOptions {
  /** Whether to execute in streaming mode */
  stream?: boolean;
  /** Custom ID (optional, automatically generated by default) */
  id?: ID;
  /** Restore from a checkpoint (checkpoint ID) */
  checkpointId?: string;
}

/**
 * AgentLoopCoordinator - Agent Loop Lifecycle Coordinator
 *
 * Key Responsibilities:
 * - Coordinates the creation, execution, suspension, resumption, and termination of AgentLoopEntities.
 * - Schedules complex multi-step operations.
 * - Manages the lifecycle of execution instances.
 *
 * Design Principles:
 * - Stateless design: Does not retain any instance variables.
 * - Dependency injection: Receives dependencies through the constructor.
 * - Process orchestration: Handles complex multi-step operations.
 */
export class AgentLoopCoordinator {
  private readonly stateTransitor: AgentLoopStateTransitor;

  constructor(
    private readonly registry: AgentLoopRegistry,
    private readonly executor: AgentLoopExecutor,
    private readonly globalContext: GlobalContext,
    eventManager?: EventRegistry, // EventRegistry type imported dynamically
    private readonly metricsCollector?: AgentLoopMetricsCollector,
  ) {
    this.stateTransitor = new AgentLoopStateTransitor(eventManager!);
  }

  /**
   * Build Entity (Internal Method)
   * @param config: Loop configuration
   * @param options: Build options
   * @returns: AgentLoopEntity instance
   */
  private async buildEntity(
    config: AgentLoopRuntimeConfig,
    options: AgentLoopExecuteOptions = {},
  ): Promise<{ entity: AgentLoopEntity; stateCoordinator: AgentStateCoordinator }> {
    // If a checkpoint ID is provided, restore from that checkpoint.
    if (options.checkpointId) {
      throw new Error(
        "From checkpoint is not yet implemented in this method. Please use AgentLoopFactory.fromCheckpoint directly.",
      );
    }

    // Create entity and state coordinator using the factory method.
    const { entity, stateCoordinator } = await AgentLoopFactory.create(
      this.globalContext,
      config,
      options,
    );

    // Register state coordinator in registry
    this.registry.registerStateCoordinator(entity.id, stateCoordinator);

    // Create and set InterruptionState for the agent loop
    const interruptionManagerFactory = this.globalContext.container.get(
      Identifiers.InterruptionState,
    );
    const interruptionManager = (
      interruptionManagerFactory as unknown as InterruptionStateFactory<InterruptionState>
    ).create(entity.id, {
      domain: "AGENT_LOOP",
      agentExecutionId: entity.id,
      iteration: entity.state.currentIteration,
    });

    // Set the interruption state on the entity so getAbortSignal() returns the same signal
    entity.setInterruptionState(interruptionManager);

    logger.debug("InterruptionState set for Agent Loop", {
      agentLoopId: entity.id,
    });

    // Setup interruption cascade propagation from parent workflow (via EventRegistry)
    if (options.parentExecutionId) {
      try {
        const eventRegistry = this.globalContext.eventRegistry;
        if (eventRegistry && interruptionManager) {
          interruptionManager.setEventRegistry(eventRegistry);
          interruptionManager.connectToParent(options.parentExecutionId);

          logger.info("Interruption cascade established for AgentLoop", {
            parentExecutionId: options.parentExecutionId,
            agentLoopId: entity.id,
          });
        }
      } catch (error) {
        // Log error but don't throw - interruption setup failure should not prevent creation
        logger.warn("Failed to setup interruption cascade for AgentLoop", {
          agentLoopId: entity.id,
          parentExecutionId: options.parentExecutionId,
          error: error instanceof Error ? error.message : String(error),
        });
      }
    }

    return { entity, stateCoordinator };
  }

  /**
   * Execute Agent Loop
   * @param config: Loop configuration
   * @param options: Execution options
   * @returns: Execution result
   */
  async execute(
    config: AgentLoopRuntimeConfig,
    options: AgentLoopExecuteOptions = {},
  ): Promise<AgentLoopResult> {
    // 1. Construct entities and state coordinator
    const { entity, stateCoordinator } = await this.buildEntity(config, options);

    logger.info("Agent Loop entity created", {
      agentLoopId: entity.id,
      maxIterations: config.maxIterations,
      toolsCount: getAvailableTools(config.availableTools).length,
    });

    // Record execution start metrics
    if (this.metricsCollector) {
      this.metricsCollector.recordExecutionStart(entity.id, entity.id);
    }

    // 2. Registering entities
    this.registry.register(entity);

    logger.debug("Agent Loop registered", { agentLoopId: entity.id });

    // 3. Start execution using state transitor
    const messageCount = stateCoordinator.getMessageCount();
    await this.stateTransitor.startAgentLoop(entity, messageCount);

    const startTime = now();

    try {
      // 4. Execute the loop
      const result = await this.executor.execute(entity, stateCoordinator);

      const duration = now() - startTime;

      // Record execution complete metrics
      if (this.metricsCollector) {
        this.metricsCollector.recordExecutionComplete(
          entity.id,
          entity.id,
          duration,
          entity.state.currentIteration,
          entity.state.toolCallCount,
          result.success,
        );
      }

      // 5. Update the status using state transitor
      // NOTE: AgentExecutionCoordinator may have already completed the entity internally
      // (e.g., executeIteration calls entity.state.complete() when LLM returns final answer).
      // Only attempt transition if still RUNNING to avoid state machine violation.
      if (result.success) {
        if (entity.getStatus() === AgentLoopStatus.RUNNING) {
          await this.stateTransitor.completeAgentLoop(entity, result);
        }
      } else {
        if (entity.getStatus() === AgentLoopStatus.RUNNING) {
          await this.stateTransitor.failAgentLoop(entity, result.error);
        }
      }

      return result;
    } catch (error) {
      const duration = now() - startTime;

      // Record error metrics
      if (this.metricsCollector) {
        this.metricsCollector.recordExecutionComplete(
          entity.id,
          entity.id,
          duration,
          entity.state.currentIteration,
          entity.state.toolCallCount,
          false,
        );
        this.metricsCollector.recordError(
          entity.id,
          error instanceof Error ? error.name : "UnknownError",
          entity.state.currentIteration,
        );
      }

      // Attempt to fail the agent loop, but gracefully handle if already completed
      try {
        await this.stateTransitor.failAgentLoop(entity, error);
      } catch (stateError) {
        logger.warn("Failed to transition agent loop to FAILED state", {
          agentLoopId: entity.id,
          currentStatus: entity.getStatus(),
          error: stateError instanceof Error ? stateError.message : String(stateError),
        });
      }
      return {
        success: false,
        iterations: entity.state.currentIteration,
        toolCallCount: entity.state.toolCallCount,
        error,
      };
    } finally {
      const cleanedCount = this.globalContext.eventRegistry.cleanupExecutionListeners(entity.id);
      if (cleanedCount > 0) {
        logger.debug("Cleaned up event listeners after agent loop execution", {
          agentLoopId: entity.id,
          cleanedCount,
        });
      }
    }
  }

  /**
   * Stream execution of the Agent Loop
   * @param config Loop configuration
   * @param options Execution options
   * @returns Stream event generator (including LLM layer events and Agent layer events)
   */
  async *executeStream(
    config: AgentLoopRuntimeConfig,
    options: AgentLoopExecuteOptions = {},
  ): AsyncGenerator<AgentLoopStreamEvent> {
    // 1. Build entities and state coordinator
    const { entity, stateCoordinator } = await this.buildEntity(config, options);

    logger.info("Agent Loop entity created for stream execution", {
      agentLoopId: entity.id,
      maxIterations: config.maxIterations,
      toolsCount: getAvailableTools(config.availableTools).length,
    });

    // 2. Registering entities
    this.registry.register(entity);

    logger.debug("Agent Loop registered for stream execution", { agentLoopId: entity.id });

    // 3. Start execution using state transitor
    const messageCount = stateCoordinator.getMessageCount();
    await this.stateTransitor.startAgentLoop(entity, messageCount);

    try {
      // 4. Stream Execution Loop
      for await (const event of this.executor.executeStream(entity, stateCoordinator)) {
        yield event;

        // Check the interrupt signal.
        if (entity.shouldPause()) {
          await this.stateTransitor.pauseAgentLoop(entity);
          return;
        }
        if (entity.shouldStop()) {
          await this.stateTransitor.cancelAgentLoop(entity, "User requested stop");
          return;
        }
      }

      // 5. Completion Status using state transitor
      await this.stateTransitor.completeAgentLoop(entity, {
        success: true,
        iterations: entity.state.currentIteration,
        toolCallCount: entity.state.toolCallCount,
      });
    } catch (error) {
      await this.stateTransitor.failAgentLoop(entity, error);
      throw error;
    } finally {
      const cleanedCount = this.globalContext.eventRegistry.cleanupExecutionListeners(entity.id);
      if (cleanedCount > 0) {
        logger.debug("Cleaned up event listeners after agent loop stream execution", {
          agentLoopId: entity.id,
          cleanedCount,
        });
      }
    }
  }

  /**
   * Start the Agent Loop (asynchronously, returns the instance ID)
   * @param config: Loop configuration
   * @param options: Execution options
   * @returns: Instance ID
   */
  async start(config: AgentLoopRuntimeConfig, options: AgentLoopExecuteOptions = {}): Promise<ID> {
    // 1. Construct entities and state coordinator
    const { entity, stateCoordinator } = await this.buildEntity(config, options);

    logger.info("Agent Loop entity created for async execution", {
      agentLoopId: entity.id,
      maxIterations: config.maxIterations,
      toolsCount: getAvailableTools(config.availableTools).length,
    });

    // 2. Registering entities
    this.registry.register(entity);

    logger.debug("Agent Loop registered for async execution", { agentLoopId: entity.id });

    // 3. Start execution using state transitor
    const messageCount = stateCoordinator.getMessageCount();
    await this.stateTransitor.startAgentLoop(entity, messageCount);

    // 4. Asynchronous execution (without waiting for results)
    this.executor
      .execute(entity, stateCoordinator)
      .then(async result => {
        if (result.success) {
          if (entity.getStatus() === AgentLoopStatus.RUNNING) {
            await this.stateTransitor.completeAgentLoop(entity, result);
          }
        } else {
          if (entity.getStatus() === AgentLoopStatus.RUNNING) {
            await this.stateTransitor.failAgentLoop(entity, result.error);
          }
        }
        this.cleanupExecutionEventListeners(entity.id);
      })
      .catch(async error => {
        // Only fail if still RUNNING to avoid state machine violation
        if (entity.getStatus() === AgentLoopStatus.RUNNING) {
          await this.stateTransitor.failAgentLoop(entity, error);
        }
        this.cleanupExecutionEventListeners(entity.id);
      });

    return entity.id;
  }

  /**
   * Cleanup execution-scoped event listeners for a given agent loop
   */
  private cleanupExecutionEventListeners(agentLoopId: ID): void {
    const cleanedCount = this.globalContext.eventRegistry.cleanupExecutionListeners(agentLoopId);
    if (cleanedCount > 0) {
      logger.debug("Cleaned up event listeners", {
        agentLoopId,
        cleanedCount,
      });
    }
  }

  /**
   * Pause execution
   * @param id Instance ID
   */
  async pause(id: ID): Promise<void> {
    logger.debug("Attempting to pause Agent Loop", { agentLoopId: id });

    const entity = await this.registry.get(id);
    if (!entity) {
      logger.warn("Agent Loop not found for pause operation", { agentLoopId: id });
      throw new Error(`AgentLoop not found: ${id}`);
    }

    if (!entity.isRunning()) {
      logger.warn("Agent Loop is not running, cannot pause", {
        agentLoopId: id,
        currentStatus: entity.getStatus(),
      });
      throw new Error(`AgentLoop is not running: ${id}`);
    }

    // Record pause metrics
    if (this.metricsCollector) {
      this.metricsCollector.recordPause(id);
    }

    // Set the pause flag
    entity.interrupt("PAUSE");
    logger.info("Agent Loop pause requested", { agentLoopId: id });
  }

  /**
   * Resume execution
   * @param id Instance ID
   * @returns Execution result
   */
  async resume(id: ID): Promise<AgentLoopResult> {
    logger.debug("Attempting to resume Agent Loop", { agentLoopId: id });

    const entity = await this.registry.get(id);
    if (!entity) {
      logger.warn("Agent Loop not found for resume operation", { agentLoopId: id });
      throw new Error(`AgentLoop not found: ${id}`);
    }

    if (!entity.isPaused()) {
      logger.warn("Agent Loop is not paused, cannot resume", {
        agentLoopId: id,
        currentStatus: entity.getStatus(),
      });
      throw new Error(`AgentLoop is not paused: ${id}`);
    }

    // Record resume metrics (pause duration tracking would require storing pause start time in entity)
    if (this.metricsCollector) {
      // For now, record resume without pause duration
      // TODO: Store pauseStartTime in entity state to calculate accurate pause duration
      this.metricsCollector.recordResume(id, 0);
    }

    // Reset the interrupt flag
    entity.resetInterrupt();

    // Resume execution using state transitor
    await this.stateTransitor.resumeAgentLoop(entity);

    const stateCoordinator = this.registry.getStateCoordinator(entity.id);
    if (!stateCoordinator) {
      logger.warn("Agent Loop state coordinator not found for resume operation", {
        agentLoopId: id,
      });
      throw new Error(`AgentLoop state coordinator not found: ${id}`);
    }

    try {
      const result = await this.executor.execute(entity, stateCoordinator);

      if (result.success) {
        if (entity.getStatus() === AgentLoopStatus.RUNNING) {
          await this.stateTransitor.completeAgentLoop(entity, result);
        }
      } else {
        if (entity.getStatus() === AgentLoopStatus.RUNNING) {
          await this.stateTransitor.failAgentLoop(entity, result.error);
        }
      }

      return result;
    } catch (error) {
      await this.stateTransitor.failAgentLoop(entity, error);
      return {
        success: false,
        iterations: entity.state.currentIteration,
        toolCallCount: entity.state.toolCallCount,
        error,
      };
    }
  }

  /**
   * Continue execution from current state
   *
   * Unlike resume() which resumes from a paused state, continue() continues
   * execution from the current state without requiring a pause.
   * This is useful for retrying after errors.
   *
   * Inspired by pi-agent-core's continue() method.
   *
   * Requirements:
   * - The last message must be user or toolResult (not assistant)
   * - The agent must not be currently running
   *
   * @param id Instance ID
   * @returns Execution result
   */
  async continue(id: ID): Promise<AgentLoopResult> {
    logger.debug("Attempting to continue Agent Loop", { agentLoopId: id });

    const entity = await this.registry.get(id);
    if (!entity) {
      logger.warn("Agent Loop not found for continue operation", { agentLoopId: id });
      throw new Error(`AgentLoop not found: ${id}`);
    }

    // Check if currently running
    if (entity.isRunning()) {
      logger.warn("Agent Loop is currently running, cannot continue", {
        agentLoopId: id,
        currentStatus: entity.getStatus(),
      });
      throw new Error(`AgentLoop is currently running: ${id}`);
    }

    // Validate last message
    const stateCoordinator = this.registry.getStateCoordinator(entity.id);
    const messages = stateCoordinator?.getMessages() ?? [];
    const lastMessage = messages[messages.length - 1];

    if (!lastMessage) {
      logger.warn("Agent Loop has no messages, cannot continue", { agentLoopId: id });
      throw new Error(`AgentLoop has no messages: ${id}`);
    }

    if (lastMessage.role === "assistant") {
      logger.warn("Agent Loop last message is assistant, cannot continue", {
        agentLoopId: id,
        lastMessageRole: lastMessage.role,
      });
      throw new Error(
        `AgentLoop last message must be user or toolResult, got: ${lastMessage.role}`,
      );
    }

    // Reset state for continuation using state transitor
    await this.stateTransitor.resumeAgentLoop(entity);

    const stateCoordinator = this.registry.getStateCoordinator(entity.id);
    if (!stateCoordinator) {
      logger.warn("Agent Loop state coordinator not found for continue operation", {
        agentLoopId: id,
      });
      throw new Error(`AgentLoop state coordinator not found: ${id}`);
    }

    try {
      const result = await this.executor.execute(entity, stateCoordinator);

      if (result.success) {
        if (entity.getStatus() === AgentLoopStatus.RUNNING) {
          await this.stateTransitor.completeAgentLoop(entity, result);
        }
      } else {
        if (entity.getStatus() === AgentLoopStatus.RUNNING) {
          await this.stateTransitor.failAgentLoop(entity, result.error);
        }
      }

      return result;
    } catch (error) {
      await this.stateTransitor.failAgentLoop(entity, error);
      return {
        success: false,
        iterations: entity.state.currentIteration,
        toolCallCount: entity.state.toolCallCount,
        error,
      };
    }
  }

  /**
   * Stop execution
   * @param id Instance ID
   */
  async stop(id: ID): Promise<void> {
    logger.debug("Attempting to stop Agent Loop", { agentLoopId: id });

    const entity = await this.registry.get(id);
    if (!entity) {
      logger.warn("Agent Loop not found for stop operation", { agentLoopId: id });
      throw new Error(`AgentLoop not found: ${id}`);
    }

    // Set a stop flag and abort the process using state transitor
    entity.interrupt("STOP");
    await this.stateTransitor.cancelAgentLoop(entity, "User requested stop");

    // Cleanup entity resources after stopping
    entity.cleanup();

    // Unregister from registry
    this.registry.unregister(id);

    // Cleanup execution-scoped event listeners
    const cleanedCount = this.globalContext.eventRegistry.cleanupExecutionListeners(id);
    if (cleanedCount > 0) {
      logger.debug("Cleaned up event listeners after agent loop stop", {
        agentLoopId: id,
        cleanedCount,
      });
    }

    logger.info("Agent Loop stopped and cleaned up", { agentLoopId: id });
  }

  /**
   * Get an instance
   * @param id: Instance ID
   */
  async get(id: ID): Promise<AgentLoopEntity | undefined> {
    return await this.registry.get(id);
  }

  /**
   * Get instance status
   * @param id: Instance ID
   */
  async getStatus(id: ID): Promise<AgentLoopStatus | undefined> {
    const entity = await this.registry.get(id);
    return entity?.getStatus();
  }

  /**
   * Get all running instances
   */
  getRunning(): AgentLoopEntity[] {
    return this.registry.getRunning();
  }

  /**
   * Get all paused instances
   */
  getPaused(): AgentLoopEntity[] {
    return this.registry.getPaused();
  }

  /**
   * Clean up the completed instances.
   */
  cleanup(): number {
    const count = this.registry.cleanupTerminated();
    if (count > 0) {
      logger.info("Agent Loop terminated instances cleaned up", { count });
    }
    return count;
  }

  /**
   * Destroy the coordinator and release all resources
   * Cleans up all running/paused/completed/failed entities and clears the registry.
   */
  destroy(): void {
    logger.info("Destroying AgentLoopCoordinator");

    // Clean up all entities in the registry
    this.registry.clear();

    logger.info("AgentLoopCoordinator destroyed");
  }
}
