/**
 * AgentLoopCoordinator - Agent Loop Lifecycle Coordinator
 *
 * Coordinates the full lifecycle management of AgentLoopEntities.
 * Refer to the design pattern of WorkflowLifecycleCoordinator.
 */

import type { ID } from "@wf-agent/types";
import type { AgentLoopRuntimeConfig, AgentLoopResult } from "@wf-agent/types";
import { AgentLoopEntity } from "../../entities/agent-loop-entity.js";
import { AgentLoopStatus } from "@wf-agent/types";
import { AgentLoopFactory, type AgentLoopEntityOptions } from "../../execution/factories/index.js";
import { AgentLoopRegistry } from "../../stores/agent-loop-registry.js";
import { AgentLoopExecutor, type AgentLoopStreamEvent } from "../executors/agent-loop-executor.js";
import { createContextualLogger } from "../../../utils/contextual-logger.js";
import { AgentLoopStateTransitor } from "./agent-loop-state-transitor.js";

const logger = createContextualLogger({ component: "AgentLoopCoordinator" });

/**
 * Execute the option
 */
export interface AgentLoopExecuteOptions extends AgentLoopEntityOptions {
  /** Whether to execute in streaming mode */
  stream?: boolean;
  /** Custom ID (optional, automatically generated by default) */
  id?: ID;
  /** Restore from a checkpoint (checkpoint ID) */
  checkpointId?: string;
}

/**
 * AgentLoopCoordinator - Agent Loop Lifecycle Coordinator
 *
 * Key Responsibilities:
 * - Coordinates the creation, execution, suspension, resumption, and termination of AgentLoopEntities.
 * - Schedules complex multi-step operations.
 * - Manages the lifecycle of execution instances.
 *
 * Design Principles:
 * - Stateless design: Does not retain any instance variables.
 * - Dependency injection: Receives dependencies through the constructor.
 * - Process orchestration: Handles complex multi-step operations.
 */
export class AgentLoopCoordinator {
  private readonly stateTransitor: AgentLoopStateTransitor;

  constructor(
    private readonly registry: AgentLoopRegistry,
    private readonly executor: AgentLoopExecutor,
    eventManager?: any, // EventRegistry type imported dynamically
  ) {
    this.stateTransitor = new AgentLoopStateTransitor(eventManager);
  }

  /**
   * Build Entity (Internal Method)
   * @param config: Loop configuration
   * @param options: Build options
   * @returns: AgentLoopEntity instance
   */
  private async buildEntity(
    config: AgentLoopRuntimeConfig,
    options: AgentLoopExecuteOptions = {},
  ): Promise<AgentLoopEntity> {
    // If a checkpoint ID is provided, restore from that checkpoint.
    if (options.checkpointId) {
      throw new Error(
        "From checkpoint is not yet implemented in this method. Please use AgentLoopFactory.fromCheckpoint directly.",
      );
    }

    // Create a new instance using the factory method.
    return AgentLoopFactory.create(config, options);
  }

  /**
   * Execute Agent Loop
   * @param config: Loop configuration
   * @param options: Execution options
   * @returns: Execution result
   */
  async execute(
    config: AgentLoopRuntimeConfig,
    options: AgentLoopExecuteOptions = {},
  ): Promise<AgentLoopResult> {
    // 1. Construct entities
    const entity = await this.buildEntity(config, options);

    logger.info("Agent Loop entity created", {
      agentLoopId: entity.id,
      maxIterations: config.maxIterations,
      toolsCount: config.availableTools?.initial.length || 0,
    });

    // 2. Registering entities
    this.registry.register(entity);

    logger.debug("Agent Loop registered", { agentLoopId: entity.id });

    // 3. Start execution using state transitor
    await this.stateTransitor.startAgentLoop(entity);

    try {
      // 4. Execute the loop
      const result = await this.executor.execute(entity);

      // 5. Update the status using state transitor
      if (result.success) {
        await this.stateTransitor.completeAgentLoop(entity, result);
      } else {
        await this.stateTransitor.failAgentLoop(entity, result.error);
      }

      return result;
    } catch (error) {
      await this.stateTransitor.failAgentLoop(entity, error);
      return {
        success: false,
        iterations: entity.state.currentIteration,
        toolCallCount: entity.state.toolCallCount,
        error,
      };
    }
  }

  /**
   * Stream execution of the Agent Loop
   * @param config Loop configuration
   * @param options Execution options
   * @returns Stream event generator (including LLM layer events and Agent layer events)
   */
  async *executeStream(
    config: AgentLoopRuntimeConfig,
    options: AgentLoopExecuteOptions = {},
  ): AsyncGenerator<AgentLoopStreamEvent> {
    // 1. Build entities
    const entity = await this.buildEntity(config, options);

    logger.info("Agent Loop entity created for stream execution", {
      agentLoopId: entity.id,
      maxIterations: config.maxIterations,
      toolsCount: config.availableTools?.initial.length || 0,
    });

    // 2. Registering entities
    this.registry.register(entity);

    logger.debug("Agent Loop registered for stream execution", { agentLoopId: entity.id });

    // 3. Start execution using state transitor
    await this.stateTransitor.startAgentLoop(entity);

    try {
      // 4. Stream Execution Loop
      for await (const event of this.executor.executeStream(entity)) {
        yield event;

        // Check the interrupt signal.
        if (entity.shouldPause()) {
          await this.stateTransitor.pauseAgentLoop(entity);
          return;
        }
        if (entity.shouldStop()) {
          await this.stateTransitor.cancelAgentLoop(entity, "User requested stop");
          return;
        }
      }

      // 5. Completion Status using state transitor
      await this.stateTransitor.completeAgentLoop(entity, {
        success: true,
        iterations: entity.state.currentIteration,
        toolCallCount: entity.state.toolCallCount,
      });
    } catch (error) {
      await this.stateTransitor.failAgentLoop(entity, error);
      throw error;
    }
  }

  /**
   * Start the Agent Loop (asynchronously, returns the instance ID)
   * @param config: Loop configuration
   * @param options: Execution options
   * @returns: Instance ID
   */
  async start(config: AgentLoopRuntimeConfig, options: AgentLoopExecuteOptions = {}): Promise<ID> {
    // 1. Construct entities
    const entity = await this.buildEntity(config, options);

    logger.info("Agent Loop entity created for async execution", {
      agentLoopId: entity.id,
      maxIterations: config.maxIterations,
      toolsCount: config.availableTools?.initial.length || 0,
    });

    // 2. Registering entities
    this.registry.register(entity);

    logger.debug("Agent Loop registered for async execution", { agentLoopId: entity.id });

    // 3. Start execution using state transitor
    await this.stateTransitor.startAgentLoop(entity);

    // 4. Asynchronous execution (without waiting for results)
    this.executor
      .execute(entity)
      .then(async result => {
        if (result.success) {
          await this.stateTransitor.completeAgentLoop(entity, result);
        } else {
          await this.stateTransitor.failAgentLoop(entity, result.error);
        }
      })
      .catch(async error => {
        await this.stateTransitor.failAgentLoop(entity, error);
      });

    return entity.id;
  }

  /**
   * Pause execution
   * @param id Instance ID
   */
  async pause(id: ID): Promise<void> {
    logger.debug("Attempting to pause Agent Loop", { agentLoopId: id });

    const entity = this.registry.get(id);
    if (!entity) {
      logger.warn("Agent Loop not found for pause operation", { agentLoopId: id });
      throw new Error(`AgentLoop not found: ${id}`);
    }

    if (!entity.isRunning()) {
      logger.warn("Agent Loop is not running, cannot pause", {
        agentLoopId: id,
        currentStatus: entity.getStatus(),
      });
      throw new Error(`AgentLoop is not running: ${id}`);
    }

    // Set the pause flag
    entity.interrupt("PAUSE");
    logger.info("Agent Loop pause requested", { agentLoopId: id });
  }

  /**
   * Resume execution
   * @param id Instance ID
   * @returns Execution result
   */
  async resume(id: ID): Promise<AgentLoopResult> {
    logger.debug("Attempting to resume Agent Loop", { agentLoopId: id });

    const entity = this.registry.get(id);
    if (!entity) {
      logger.warn("Agent Loop not found for resume operation", { agentLoopId: id });
      throw new Error(`AgentLoop not found: ${id}`);
    }

    if (!entity.isPaused()) {
      logger.warn("Agent Loop is not paused, cannot resume", {
        agentLoopId: id,
        currentStatus: entity.getStatus(),
      });
      throw new Error(`AgentLoop is not paused: ${id}`);
    }

    // Reset the interrupt flag
    entity.resetInterrupt();

    // Resume execution using state transitor
    await this.stateTransitor.resumeAgentLoop(entity);

    try {
      const result = await this.executor.execute(entity);

      if (result.success) {
        await this.stateTransitor.completeAgentLoop(entity, result);
      } else {
        await this.stateTransitor.failAgentLoop(entity, result.error);
      }

      return result;
    } catch (error) {
      await this.stateTransitor.failAgentLoop(entity, error);
      return {
        success: false,
        iterations: entity.state.currentIteration,
        toolCallCount: entity.state.toolCallCount,
        error,
      };
    }
  }

  /**
   * Continue execution from current state
   *
   * Unlike resume() which resumes from a paused state, continue() continues
   * execution from the current state without requiring a pause.
   * This is useful for retrying after errors.
   *
   * Inspired by pi-agent-core's continue() method.
   *
   * Requirements:
   * - The last message must be user or toolResult (not assistant)
   * - The agent must not be currently running
   *
   * @param id Instance ID
   * @returns Execution result
   */
  async continue(id: ID): Promise<AgentLoopResult> {
    logger.debug("Attempting to continue Agent Loop", { agentLoopId: id });

    const entity = this.registry.get(id);
    if (!entity) {
      logger.warn("Agent Loop not found for continue operation", { agentLoopId: id });
      throw new Error(`AgentLoop not found: ${id}`);
    }

    // Check if currently running
    if (entity.isRunning()) {
      logger.warn("Agent Loop is currently running, cannot continue", {
        agentLoopId: id,
        currentStatus: entity.getStatus(),
      });
      throw new Error(`AgentLoop is currently running: ${id}`);
    }

    // Validate last message
    const messages = entity.getMessages();
    const lastMessage = messages[messages.length - 1];

    if (!lastMessage) {
      logger.warn("Agent Loop has no messages, cannot continue", { agentLoopId: id });
      throw new Error(`AgentLoop has no messages: ${id}`);
    }

    if (lastMessage.role === "assistant") {
      logger.warn("Agent Loop last message is assistant, cannot continue", {
        agentLoopId: id,
        lastMessageRole: lastMessage.role,
      });
      throw new Error(
        `AgentLoop last message must be user or toolResult, got: ${lastMessage.role}`,
      );
    }

    // Reset state for continuation using state transitor
    await this.stateTransitor.resumeAgentLoop(entity);

    try {
      const result = await this.executor.execute(entity);

      if (result.success) {
        await this.stateTransitor.completeAgentLoop(entity, result);
      } else {
        await this.stateTransitor.failAgentLoop(entity, result.error);
      }

      return result;
    } catch (error) {
      await this.stateTransitor.failAgentLoop(entity, error);
      return {
        success: false,
        iterations: entity.state.currentIteration,
        toolCallCount: entity.state.toolCallCount,
        error,
      };
    }
  }

  /**
   * Stop execution
   * @param id Instance ID
   */
  async stop(id: ID): Promise<void> {
    logger.debug("Attempting to stop Agent Loop", { agentLoopId: id });

    const entity = this.registry.get(id);
    if (!entity) {
      logger.warn("Agent Loop not found for stop operation", { agentLoopId: id });
      throw new Error(`AgentLoop not found: ${id}`);
    }

    // Set a stop flag and abort the process using state transitor
    entity.interrupt("STOP");
    await this.stateTransitor.cancelAgentLoop(entity, "User requested stop");
  }

  /**
   * Get an instance
   * @param id: Instance ID
   */
  get(id: ID): AgentLoopEntity | undefined {
    return this.registry.get(id);
  }

  /**
   * Get instance status
   * @param id: Instance ID
   */
  getStatus(id: ID): AgentLoopStatus | undefined {
    return this.registry.get(id)?.getStatus();
  }

  /**
   * Get all running instances
   */
  getRunning(): AgentLoopEntity[] {
    return this.registry.getRunning();
  }

  /**
   * Get all paused instances
   */
  getPaused(): AgentLoopEntity[] {
    return this.registry.getPaused();
  }

  /**
   * Clean up the completed instances.
   */
  cleanup(): number {
    const count = this.registry.cleanupCompleted();
    if (count > 0) {
      logger.info("Agent Loop completed instances cleaned up", { count });
    }
    return count;
  }
}
