[package]
name = "tui-style"
version.workspace = true
edition.workspace = true
description = "Low-level TUI implementation crate (tui-style)"

[dependencies]
ratatui = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
unicode-width = { workspace = true }
unicode-segmentation = { workspace = true }
tui-clock = { path = "../tui-clock" }
tui-terminal = { path = "../tui-terminal" }

[features]
default = []

[dev-dependencies]
tempfile = { workspace = true }
