[package]
name = "tui-style"
version.workspace = true
edition.workspace = true
description = "Low-level TUI implementation crate (tui-style)"

[dependencies]
wf-common = { workspace = true }
wf-types = { workspace = true }
wf-core = { workspace = true }
ratatui = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
crossterm = { workspace = true }
libc = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tui-clock = { path = "../tui-clock" }

[features]
default = []

[dev-dependencies]
tempfile = { workspace = true }
