// Code generated by wit-bindgen-go. DO NOT EDIT.

package lifecycle

import (
	"go.bytecodealliance.org/cm"
)

func lift_HookInput(f0 *uint8, f1 uint32, f2 *uint8, f3 uint32) (v HookInput) {
	v.PluginID = cm.LiftString[string](f0, f1)
	v.Config = cm.LiftString[string](f2, f3)
	return
}
