// Code generated by wit-bindgen-go. DO NOT EDIT.

package lifecycle

import (
	"go.bytecodealliance.org/cm"
)

// Exports represents the caller-defined exports from "wf:plugin/lifecycle@0.1.0-draft".
var Exports struct {
	// OnLoad represents the caller-defined, exported function "on-load".
	//
	//	on-load: func(input: hook-input) -> result<_, string>
	OnLoad func(input HookInput) (result cm.Result[string, struct{}, string])

	// OnActivate represents the caller-defined, exported function "on-activate".
	//
	//	on-activate: func(input: hook-input) -> result<_, string>
	OnActivate func(input HookInput) (result cm.Result[string, struct{}, string])

	// OnDeactivate represents the caller-defined, exported function "on-deactivate".
	//
	//	on-deactivate: func() -> result<_, string>
	OnDeactivate func() (result cm.Result[string, struct{}, string])

	// OnUnload represents the caller-defined, exported function "on-unload".
	//
	//	on-unload: func() -> result<_, string>
	OnUnload func() (result cm.Result[string, struct{}, string])

	// OnConfigChange represents the caller-defined, exported function "on-config-change".
	//
	//	on-config-change: func(config: string) -> result<_, string>
	OnConfigChange func(config string) (result cm.Result[string, struct{}, string])
}
