// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package lifecycle represents the exported interface "wf:plugin/lifecycle@0.1.0-draft".
package lifecycle

import (
	"go.bytecodealliance.org/cm"
)

// HookInput represents the record "wf:plugin/lifecycle@0.1.0-draft#hook-input".
//
// Hook input envelope, mirroring the JSON passed today.
//
//	record hook-input {
//		plugin-id: string,
//		config: string,
//	}
type HookInput struct {
	_        cm.HostLayout `json:"-"`
	PluginID string        `json:"plugin-id"`
	Config   string        `json:"config"`
}
