[package]
name = "wf-sandbox"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
tokio = { workspace = true, features = ["sync", "time", "fs", "process", "io-util"] }
tracing.workspace = true
thiserror.workspace = true
async-trait.workspace = true
futures.workspace = true
regex.workspace = true
serde_json.workspace = true
shlex.workspace = true
blake3.workspace = true

wf-types = { path = "../../foundation/wf-types" }
wf-common = { path = "../../foundation/wf-common" }

mlua = { workspace = true, optional = true }
libc.workspace = true

[features]
default = []
lua = ["dep:mlua"]
