[package]
name = "wf-sandbox"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
tokio = { workspace = true, features = ["sync", "time", "fs", "process", "io-util"] }
tracing.workspace = true
thiserror.workspace = true
async-trait.workspace = true
futures.workspace = true
regex = "1.10"
serde_json = "1"
shlex = "2.0"
blake3.workspace = true

wf-types = { path = "../../foundation/wf-types" }
wf-common = { path = "../../foundation/wf-common" }

mlua = { version = "0.9", optional = true, default-features = false, features = ["luajit"] }
libc = "0.2"

[features]
default = ["lua-mlua-sandbox"]
lua-mlua-sandbox = ["dep:mlua"]
