pub mod dead_loop_detector;
pub mod error;
pub mod client;
pub mod client_factory;
pub mod formatter_helpers;
pub mod message_helper;
pub mod messaging;
pub mod partial_json_parser;
pub mod profile_manager;
pub mod tool_call_parser;
pub mod wrapper;
pub mod formatters;
pub mod message_stream;

pub use dead_loop_detector::{DeadLoopDetectionConfig, DeadLoopDetector, LoopDetectionResult};
pub use error::{LlmError, LlmResult};
pub use client::LlmClient;
pub use client_factory::ClientFactory;
pub use message_helper::{count_total_chars, extract_text_content, merge_consecutive_messages, truncate_message};
pub use messaging::conversation_session::{ConversationSession, ConversationState};
pub use messaging::cross_boundary_converter::{BoundaryType, CrossBoundaryConverter};
pub use messaging::dynamic_injection::DynamicInjection;
pub use messaging::history_converter::{HistoryConverter, HistoryFormat};
pub use messaging::message_array_manager::MessageArrayManager;
pub use messaging::message_context_registry::{MessageContextRegistry, NamedMessageContext};
pub use messaging::visible_range_calculator::{VisibleRange, VisibleRangeCalculator, VisibilityScope};
pub use partial_json_parser::{PartialParseResult, parse_partial_json};
pub use profile_manager::ProfileManager;
pub use tool_call_parser::{parse_anthropic_tool_use, parse_tool_calls_from_json};
pub use wrapper::LlmWrapper;
pub use formatters::{LlmFormatter, OpenaiChatFormatter, OpenaiResponseFormatter, AnthropicFormatter, GeminiNativeFormatter, GeminiOpenaiFormatter, create_formatter};
pub use message_stream::MessageStream;
