// Code generated by wit-bindgen-go. DO NOT EDIT.

package hostlog

// This file contains wasmimport and wasmexport declarations for "wf:plugin@0.1.0-draft".

//go:wasmimport wf:plugin/host-log@0.1.0-draft log
//go:noescape
func wasmimport_Log(level0 uint32, message0 *uint8, message1 uint32)
