// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package hostlog represents the imported interface "wf:plugin/host-log@0.1.0-draft".
package hostlog

import (
	"go.bytecodealliance.org/cm"
)

// Log represents the imported function "log".
//
// Structured guest-to-host log. Levels: 0 trace, 1 debug, 2 info,
// 3 warn, 4 and above error. Best-effort: over-long messages are
// truncated and the call never fails the guest.
//
//	log: func(level: u32, message: string)
//
//go:nosplit
func Log(level uint32, message string) {
	level0 := (uint32)(level)
	message0, message1 := cm.LowerString(message)
	wasmimport_Log((uint32)(level0), (*uint8)(message0), (uint32)(message1))
	return
}
