// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package contributions represents the exported interface "wf:plugin/contributions@0.1.0-draft".
package contributions

import (
	"go.bytecodealliance.org/cm"
)

// MiddlewareDecl represents the record "wf:plugin/contributions@0.1.0-draft#middleware-decl".
//
//	record middleware-decl {
//		phase: string,
//		priority: s32,
//	}
type MiddlewareDecl struct {
	_        cm.HostLayout `json:"-"`
	Phase    string        `json:"phase"`
	Priority int32         `json:"priority"`
}

// Declaration represents the record "wf:plugin/contributions@0.1.0-draft#declaration".
//
// Contribution declaration, mirroring `wf_register` JSON today.
//
//	record declaration {
//		node-types: list<string>,
//		tool-types: list<string>,
//		llm-providers: list<string>,
//		event-handlers: list<string>,
//		middleware: list<middleware-decl>,
//	}
type Declaration struct {
	_             cm.HostLayout           `json:"-"`
	NodeTypes     cm.List[string]         `json:"node-types"`
	ToolTypes     cm.List[string]         `json:"tool-types"`
	LlmProviders  cm.List[string]         `json:"llm-providers"`
	EventHandlers cm.List[string]         `json:"event-handlers"`
	Middleware    cm.List[MiddlewareDecl] `json:"middleware"`
}
