// Code generated by wit-bindgen-go. DO NOT EDIT.

package contributions

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "wf:plugin@0.1.0-draft".

//go:wasmexport wf:plugin/contributions@0.1.0-draft#register
//export wf:plugin/contributions@0.1.0-draft#register
func wasmexport_Register() (result *Declaration) {
	result_ := Exports.Register()
	result = &result_
	return
}

//go:wasmexport wf:plugin/contributions@0.1.0-draft#dispatch
//export wf:plugin/contributions@0.1.0-draft#dispatch
func wasmexport_Dispatch(handlerType0 *uint8, handlerType1 uint32, handlerName0 *uint8, handlerName1 uint32, inputJson0 *uint8, inputJson1 uint32) (result *cm.Result[string, string, string]) {
	handlerType := cm.LiftString[string]((*uint8)(handlerType0), (uint32)(handlerType1))
	handlerName := cm.LiftString[string]((*uint8)(handlerName0), (uint32)(handlerName1))
	inputJSON := cm.LiftString[string]((*uint8)(inputJson0), (uint32)(inputJson1))
	result_ := Exports.Dispatch(handlerType, handlerName, inputJSON)
	result = &result_
	return
}
