// Code generated by wit-bindgen-go. DO NOT EDIT.

package contributions

import (
	"go.bytecodealliance.org/cm"
)

// Exports represents the caller-defined exports from "wf:plugin/contributions@0.1.0-draft".
var Exports struct {
	// Register represents the caller-defined, exported function "register".
	//
	//	register: func() -> declaration
	Register func() (result Declaration)

	// Dispatch represents the caller-defined, exported function "dispatch".
	//
	// Single dispatch entry, mirroring `wf_dispatch` today. Payloads stay
	// JSON strings by design (cross-language guests, small control docs);
	// structured payloads would be a breaking contract upgrade.
	//
	//	dispatch: func(handler-type: string, handler-name: string, input-json: string)
	//	-> result<string, string>
	Dispatch func(handlerType string, handlerName string, inputJSON string) (result cm.Result[string, string, string])
}
