/**
 * Lua Builtin-hook Strategy
 *
 * Wraps Lua code with secure builtins before execution via subprocess.
 * Replaces io.open, os.execute, and disables dangerous functions.
 *
 * Architecture reference: docs/infra/sandbox/strategies/lua-sandbox.md
 */

import type {
  SandboxPolicy,
  LuaPolicy,
  ScriptExecutionResult,
  StrategyExecuteOptions,
} from "@wf-agent/types";
import type { StrategyImplementation } from "../../types.js";
import { getTerminalService, type TerminalService } from "../../../terminal/index.js";
import * as fs from "node:fs";
import * as path from "node:path";
import * as os from "node:os";
import { checkLuaAvailable, DEFAULT_DENIED_MODULES } from "./base.js";

/**
 * Lua Builtin-hook Strategy
 *
 * Generates a wrapped Lua script that:
 *   - Replaces require with a safe version (module whitelist/blacklist)
 *   - Replaces io.open with a safe version (checks write path whitelist)
 *   - Disables os.execute, os.remove, os.rename, etc.
 *   - Disables loadstring, load (dynamic code execution)
 */
export class LuaBuiltinHookStrategy implements StrategyImplementation<ScriptExecutionResult> {
  id = "builtin-hook";
  name = "Lua Builtin Hook";
  description = "Lua script sandboxing by hooking builtins and restricting module loading";
  priority = 20;

  private terminalService: TerminalService;

  constructor(terminalService?: TerminalService) {
    this.terminalService = terminalService || getTerminalService();
  }

  isAvailable(): boolean {
    return checkLuaAvailable();
  }

  async execute(
    options: StrategyExecuteOptions,
    policy: SandboxPolicy,
  ): Promise<ScriptExecutionResult> {
    const startTime = Date.now();
    const code = options.command;
    const luaPolicy: LuaPolicy = {
      allowedModules: policy.lua?.allowedModules ?? [],
      deniedModules: policy.lua?.deniedModules ?? DEFAULT_DENIED_MODULES,
      allowOsExecute: policy.lua?.allowOsExecute ?? false,
      restrictIoOpen: policy.lua?.restrictIoOpen ?? true,
      allowDynamicLoad: policy.lua?.allowDynamicLoad ?? false,
    };

    if (!code) {
      return {
        success: false,
        scriptName: "sandbox-lua",
        executionTime: Date.now() - startTime,
        error: "Empty Lua code",
      };
    }

    const vfsEnabled = !!options.vfs;
    const writableDirs = vfsEnabled && options.cwd ? [options.cwd] : [];
    const wrappedCode = this.wrapWithSandbox(code, luaPolicy, vfsEnabled, writableDirs);
    const tmpFile = path.join(
      os.tmpdir(),
      `sandbox-lua-${Date.now()}-${Math.random().toString(36).slice(2, 8)}.lua`,
    );

    try {
      fs.writeFileSync(tmpFile, wrappedCode, "utf-8");
      const result = await this.terminalService.executeOneOff(`lua "${tmpFile}"`, {
        cwd: options.cwd,
        env: {
          ...options.env,
          LUA_PATH: "",
          LUA_CPATH: "",
        },
        timeout: options.timeout ?? policy.resource?.timeoutLimit,
      });

      return {
        success: result.success,
        scriptName: "sandbox-lua",
        stdout: result.stdout,
        stderr: result.stderr,
        exitCode: result.exitCode,
        executionTime: Date.now() - startTime,
        error: result.error,
      };
    } catch (error) {
      return {
        success: false,
        scriptName: "sandbox-lua",
        executionTime: Date.now() - startTime,
        error: error instanceof Error ? error.message : String(error),
      };
    } finally {
      try {
        fs.unlinkSync(tmpFile);
      } catch {
        // Ignore cleanup errors
      }
    }
  }

  /**
   * Generate a wrapped Lua script with security hooks.
   * When VFS is enabled, write operations are allowed within the workspace
   * directory (the VFS delta layer on the Node.js side handles CoW).
   */
  wrapWithSandbox(
    code: string,
    policy: LuaPolicy,
    vfsEnabled: boolean = false,
    writableDirs: string[] = [],
  ): string {
    const restrictOpen = policy.restrictIoOpen;
    const allowOsExecute = policy.allowOsExecute;
    const allowDynamicLoad = policy.allowDynamicLoad;

    // Build the sandbox wrapper
    const wrapper: string[] = [];

    // Store original functions
    wrapper.push(`-- ═══════════════════════════════════════════════════════════════════════════`);
    wrapper.push(`-- Lua Sandbox Wrapper - Generated by LuaBuiltinHookStrategy`);
    wrapper.push(`-- ═══════════════════════════════════════════════════════════════════════════`);
    wrapper.push(``);
    wrapper.push(`local _original_require = require`);
    wrapper.push(`local _original_open = io.open`);
    wrapper.push(
      `local _DENIED_MODULES = { ${policy.deniedModules.map(m => `["${m}"] = true`).join(", ")} }`,
    );
    wrapper.push(
      `local _ALLOWED_MODULES = { ${policy.allowedModules.map(m => `["${m}"] = true`).join(", ")} }`,
    );
    wrapper.push(`local _ALLOW_DYNAMIC_LOAD = ${allowDynamicLoad}`);
    wrapper.push(`local _ALLOW_OS_EXECUTE = ${allowOsExecute}`);
    wrapper.push(`local _VFS_ENABLED = ${vfsEnabled}`);
    wrapper.push(
      `local _WRITABLE_DIRS = { ${writableDirs.map(d => `"${d.replace(/\\/g, "\\\\")}"`).join(", ")} }`,
    );
    wrapper.push(``);

    // Safe require function
    wrapper.push(`-- ── Safe require with module whitelist/blacklist ──`);
    wrapper.push(`function require(name)`);
    wrapper.push(`    local moduleName = name:match("^([^%.]+)") or name`);
    wrapper.push(`    if next(_ALLOWED_MODULES) ~= nil and not _ALLOWED_MODULES[moduleName] then`);
    wrapper.push(`        error("Module not allowed: " .. name)`);
    wrapper.push(`    end`);
    wrapper.push(`    if _DENIED_MODULES[moduleName] then`);
    wrapper.push(`        error("Module denied: " .. name)`);
    wrapper.push(`    end`);
    wrapper.push(`    return _original_require(name)`);
    wrapper.push(`end`);
    wrapper.push(``);

    // Disable dangerous os functions
    wrapper.push(`-- ── Disable dangerous os functions ──`);
    wrapper.push(`if not _ALLOW_OS_EXECUTE then`);
    wrapper.push(`    os.execute = nil`);
    wrapper.push(`end`);
    wrapper.push(`os.remove = nil`);
    wrapper.push(`os.rename = nil`);
    wrapper.push(`os.exit = nil`);
    wrapper.push(`os.setlocale = nil`);
    wrapper.push(`os.tmpname = nil`);
    wrapper.push(``);

    // Disable dynamic code execution
    wrapper.push(`-- ── Disable dynamic code execution ──`);
    wrapper.push(`if not _ALLOW_DYNAMIC_LOAD then`);
    wrapper.push(`    loadstring = nil`);
    wrapper.push(`    load = nil`);
    wrapper.push(`end`);
    wrapper.push(``);

    // Safe io.open
    if (restrictOpen) {
      wrapper.push(`-- ── Safe io.open - restrict write operations ──`);
      wrapper.push(`function io.open(path, mode)`);
      wrapper.push(`    local m = mode or "r"`);
      wrapper.push(`    if m:find("[wax+]") then`);
      wrapper.push(`        if _VFS_ENABLED then`);
      wrapper.push(`            local absPath = path`);
      wrapper.push(`            for _, wdir in ipairs(_WRITABLE_DIRS) do`);
      wrapper.push(`                if absPath:sub(1, #wdir) == wdir then`);
      wrapper.push(`                    return _original_open(path, mode)`);
      wrapper.push(`                end`);
      wrapper.push(`            end`);
      wrapper.push(`            error("Write denied (outside workspace): " .. path)`);
      wrapper.push(`        else`);
      wrapper.push(`            error("Write denied: " .. path)`);
      wrapper.push(`        end`);
      wrapper.push(`    end`);
      wrapper.push(`    return _original_open(path, mode)`);
      wrapper.push(`end`);
      wrapper.push(``);
    }

    // Disable other dangerous io functions
    wrapper.push(`-- ── Disable other dangerous io functions ──`);
    wrapper.push(`io.popen = nil`);
    wrapper.push(`io.tmpfile = nil`);
    wrapper.push(``);

    // User code
    wrapper.push(`-- ═══════════════════════════════════════════════════════════════════════════`);
    wrapper.push(`-- User code follows`);
    wrapper.push(`-- ═══════════════════════════════════════════════════════════════════════════`);
    wrapper.push(code);

    return wrapper.join("\n");
  }
}
