// Minimal component-model wasm guest written in Go, targeting the
// `wf:plugin/plugin@0.1.0-draft` world declared in wit/plugin.wit.
//
// Build with TinyGo using the bindings generated by wit-bindgen-go under
// `internal/`:
//
//	make build
//
// The generated glue owns the canonical-ABI marshalling (struct and string
// results are written through a return area); this file only wires the
// guest's handlers into the generated `Exports` slots. Hand-written
// `//go:wasmexport` functions cannot express these signatures because TinyGo
// only supports scalar parameters and results.
package main

import (
	"go.bytecodealliance.org/cm"

	"wf-agent/examples/wasm-go-echo/internal/wf/plugin/contributions"
	"wf-agent/examples/wasm-go-echo/internal/wf/plugin/lifecycle"
)

func init() {
	lifecycle.Exports.OnLoad = func(input lifecycle.HookInput) cm.Result[string, struct{}, string] {
		return cm.OK[cm.Result[string, struct{}, string]](struct{}{})
	}
	lifecycle.Exports.OnActivate = func(input lifecycle.HookInput) cm.Result[string, struct{}, string] {
		return cm.OK[cm.Result[string, struct{}, string]](struct{}{})
	}
	lifecycle.Exports.OnDeactivate = func() cm.Result[string, struct{}, string] {
		return cm.OK[cm.Result[string, struct{}, string]](struct{}{})
	}
	lifecycle.Exports.OnUnload = func() cm.Result[string, struct{}, string] {
		return cm.OK[cm.Result[string, struct{}, string]](struct{}{})
	}
	lifecycle.Exports.OnConfigChange = func(config string) cm.Result[string, struct{}, string] {
		return cm.OK[cm.Result[string, struct{}, string]](struct{}{})
	}

	contributions.Exports.Register = func() contributions.Declaration {
		return contributions.Declaration{
			NodeTypes:     cm.ToList([]string{}),
			ToolTypes:     cm.ToList([]string{"echo"}),
			LlmProviders:  cm.ToList([]string{}),
			EventHandlers: cm.ToList([]string{}),
			Middleware:    cm.ToList([]contributions.MiddlewareDecl{}),
		}
	}
	contributions.Exports.Dispatch = func(handlerType, handlerName, inputJSON string) cm.Result[string, string, string] {
		if handlerType == "tool" && handlerName == "echo" {
			return cm.OK[cm.Result[string, string, string]](`{"result":{"echo":true}}`)
		}
		return cm.Err[cm.Result[string, string, string]]("unknown handler: " + handlerType + "/" + handlerName)
	}
}

func main() {}
