/**
 * Assistant System Prompt Template
 * Used to define system prompts for general assistants
 *
 * This template is generated by combining predefined segments and supports the injection of dynamic tool instructions.
 */

import type { PromptTemplate } from "@wf-agent/prompt-templates";
import {
  fragmentRegistry,
  initializeFragmentRegistry,
  ASSISTANT_SYSTEM_PROMPT_FRAGMENTS,
  buildCompleteSystemPrompt,
} from "../fragments/index.js";

/**
 * Initialize segment registry
 */
function ensureInitialized(): void {
  if (!fragmentRegistry.has("sdk.fragments.role.assistant")) {
    initializeFragmentRegistry();
  }
}

/**
 * Construct assistant system prompt content
 *
 * @param toolListDescription Optional dynamic tool descriptions
 * @returns Complete system prompt content
 */
export function buildAssistantSystemPromptContent(toolListDescription?: string): string {
  ensureInitialized();

  return buildCompleteSystemPrompt({
    fragmentIds: ASSISTANT_SYSTEM_PROMPT_FRAGMENTS,
    toolListDescription,
  });
}

/**
 * Assistant System Prompt Words Template
 *
 * This is a template based on the combination of segments, where "content" represents the default combination (excluding tool instructions).
 */
export const ASSISTANT_SYSTEM_TEMPLATE: PromptTemplate = {
  id: "system.assistant",
  name: "Assistant System Prompt",
  description: "Generic Assistant System Prompt Words (based on fragment combinations)",
  category: "system",
  content: buildAssistantSystemPromptContent(),
  variables: [],
};

/**
 * List of assistant system prompt phrase IDs
 * For custom combination or extension purposes
 */
export { ASSISTANT_SYSTEM_PROMPT_FRAGMENTS };
