/**
 * Programmer System Prompt Template
 * Used to define system prompts for programmer assistants
 *
 * This template is generated by combining predefined segments and supports the injection of dynamic tool instructions.
 */

import type { PromptTemplate } from "@wf-agent/prompt-templates";
import {
  fragmentRegistry,
  initializeFragmentRegistry,
  buildCompleteSystemPrompt,
  CODER_SYSTEM_PROMPT_FRAGMENTS,
} from "../fragments/index.js";

/**
 * Initialize fragment registry
 */
function ensureInitialized(): void {
  if (!fragmentRegistry.has("sdk.fragments.role.coder")) {
    initializeFragmentRegistry();
  }
}

/**
 * Constructing the programmer assistant system prompt content
 *
 * @param toolListDescription (Optional) Description of the dynamic tools
 * @returns The complete system prompt content
 */
export function buildCoderSystemPromptContent(toolListDescription?: string): string {
  ensureInitialized();

  return buildCompleteSystemPrompt({
    fragmentIds: CODER_SYSTEM_PROMPT_FRAGMENTS,
    toolListDescription,
  });
}

/**
 * Programmer System Prompt Template
 *
 * This is a template based on the combination of segments, with "content" being the default combination (excluding tool instructions).
 */
export const CODER_SYSTEM_TEMPLATE: PromptTemplate = {
  id: "system.coder",
  name: "Coder System Prompt",
  description: "Programming Assistant System Prompt Words (based on fragment combinations)",
  category: "system",
  content: buildCoderSystemPromptContent(),
  variables: [],
};

/**
 * List of programmer system prompt phrase IDs
 * Used for custom combination or extension
 */
export { CODER_SYSTEM_PROMPT_FRAGMENTS };
