[package]
name = "tui-markdown"
version.workspace = true
edition.workspace = true
description = "Low-level TUI implementation crate (tui-markdown)"

[dependencies]
ratatui = { workspace = true }
pulldown-cmark = { workspace = true }
unicode-width = { workspace = true }
unicode-segmentation = { workspace = true }
tui-style = { path = "../tui-style" }

[features]
default = []
